services:
  api:
    image: matejrupnik/breakpoint:latest
    env_file:
      - .env
    ports:
      - "4000:4000"

  db:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_DB: ${BREAKPOINT_DB}
      POSTGRES_USER: ${BREAKPOINT_DB_USER}
      POSTGRES_PASSWORD: ${BREAKPOINT_DB_PASSWORD}
#      PG_DATA: /var/lib/postgresql/data/pgdata
#      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/docker-entrypoint-initdb.d
#      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"